# Generated by Django 4.2 on 2026-02-26 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('trialing', 'Trialing'), ('canceled', 'Canceled')], default='inactive', max_length=20)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('preferred_language', models.CharField(default='fr', max_length=10)),
                ('preferred_reciter', models.CharField(default='ar.alafasy', max_length=50)),
                ('show_transliteration', models.BooleanField(default=True)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('total_verses_read', models.PositiveIntegerField(default=0)),
                ('total_tasbih', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
