services:
  - type: web
    name: nurcoran-web
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate --no-input
    startCommand: gunicorn config.wsgi:application