# Generated by Django 4.2 on 2026-02-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_arabic', models.TextField()),
                ('text_french', models.TextField()),
                ('narrator', models.CharField(max_length=120)),
                ('source', models.CharField(max_length=120)),
                ('reference', models.CharField(max_length=120)),
                ('display_date', models.DateField(unique=True)),
            ],
            options={
                'ordering': ['-display_date'],
            },
        ),
    ]

