# Generated by Django 4.2 on 2026-04-25 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_forum_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='post_type',
            field=models.CharField(choices=[('verse', 'Verset + reflexion'), ('dua', 'Dua'), ('hadith', 'Hadith'), ('question', 'Question')], default='verse', max_length=20),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='verse_reference',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
