# Generated by Django 4.2 on 2026-04-25 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayernotificationsetting',
            name='tahajjud',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PrayerReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_name', models.CharField(choices=[('Fajr', 'Fajr'), ('Dhuhr', 'Dhuhr'), ('Asr', 'Asr'), ('Maghrib', 'Maghrib'), ('Isha', 'Isha'), ('Tahajjud', 'Tahajjud')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('delay_minutes', models.PositiveSmallIntegerField(default=0)),
                ('sound', models.CharField(choices=[('adhan', 'Adhan'), ('beep', 'Bip')], default='adhan', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prayer_name'],
                'unique_together': {('user', 'prayer_name')},
            },
        ),
    ]
