# Generated by Django 4.2 on 2026-02-26 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AzkarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zikr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_arabic', models.TextField()),
                ('transliteration', models.TextField(blank=True)),
                ('translation', models.TextField(blank=True)),
                ('repetitions', models.PositiveIntegerField(default=1)),
                ('audio_url', models.URLField(blank=True)),
                ('is_premium_audio', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azkar', to='azkar.azkarcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ZikrCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zikr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azkar.zikr')),
            ],
            options={
                'unique_together': {('user', 'zikr')},
            },
        ),
    ]

