# Generated by Django 4.2 on 2026-02-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsmaName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name_arabic', models.CharField(max_length=100)),
                ('transliteration', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
