# Generated by Django 4.2 on 2026-04-25 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asmaname',
            name='audio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='asmaname',
            name='hadith_reference',
            field=models.CharField(blank=True, default='Invoquez Allah par Ses plus beaux Noms.', max_length=255),
        ),
        migrations.CreateModel(
            name='LearnedName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorized_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learners', to='asma.asmaname')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_names', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-memorized_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
