RECITERS_CATALOG = [
    {"name": "Mishary Rashid Alafasy", "country": "Koweit", "wiki_title": "Mishary_Rashid_Alafasy"},
    {"name": "Abdul Rahman Al-Sudais", "country": "Arabie saoudite", "wiki_title": "Abdul_Rahman_Al-Sudais"},
    {"name": "Saad Al-Ghamdi", "country": "Arabie saoudite", "wiki_title": "Saad_Al-Ghamdi"},
    {"name": "Maher Al-Muaiqly", "country": "Arabie saoudite", "wiki_title": "Maher_Al_Muaiqly"},
    {"name": "Yasser Al-Dosari", "country": "Arabie saoudite", "wiki_title": "Yasser_Al-Dosari"},
    {"name": "Abdullah Basfar", "country": "Arabie saoudite", "wiki_title": "Abdullah_Basfar"},
    {"name": "Ahmed Al-Ajmi", "country": "Koweit", "wiki_title": "Ahmed_Al-Ajmi"},
    {"name": "Muhammad Ayyub", "country": "Arabie saoudite", "wiki_title": "Muhammad_Ayyub"},
    {"name": "Ali Jaber", "country": "Arabie saoudite", "wiki_title": "Ali_Jaber"},
    {"name": "Hani Ar-Rifai", "country": "Arabie saoudite", "wiki_title": "Hani_Ar_Rifai"},
    {"name": "Abdul Basit Abdul Samad", "country": "Egypte", "wiki_title": "Abdul_Basit_'Abd_us-Samad"},
    {"name": "Mahmoud Khalil Al-Husary", "country": "Egypte", "wiki_title": "Mahmoud_Khalil_Al-Hussary"},
    {"name": "Muhammad Siddiq Al-Minshawi", "country": "Egypte", "wiki_title": "Mohamed_Siddiq_El-Minshawi"},
    {"name": "Mustafa Ismail", "country": "Egypte", "wiki_title": "Mustafa_Ismail"},
    {"name": "Khalil Al-Hussary", "country": "Egypte", "wiki_title": "Mahmoud_Khalil_Al-Hussary"},
    {"name": "Nasser Al-Qatami", "country": "Arabie saoudite", "wiki_title": "Nasser_Al-Qatami"},
    {"name": "Saud Al-Shuraim", "country": "Arabie saoudite", "wiki_title": "Saud_Al-Shuraim"},
    {"name": "Fares Abbad", "country": "Yemen", "wiki_title": "Fares_Abbad"},
    {"name": "Abdullah Awad Al Juhany", "country": "Arabie saoudite", "wiki_title": "Abdullah_Awad_Al_Juhany"},
    {"name": "Bandar Baleela", "country": "Arabie saoudite", "wiki_title": "Bandar_Baleela"},
    {"name": "Idris Abkar", "country": "Arabie saoudite", "wiki_title": "Idris_Abkar"},
    {"name": "Noreen Muhammad Siddiq", "country": "Soudan", "wiki_title": "Noreen_Muhammad_Siddiq"},
    {"name": "Muhammad Jibreel", "country": "Egypte", "wiki_title": "Muhammad_Jibreel"},
    {"name": "Abu Bakr Al-Shatri", "country": "Arabie saoudite", "wiki_title": "Abu_Bakr_al-Shatri"},
    {"name": "Salah Al Budair", "country": "Arabie saoudite", "wiki_title": "Salah_Al_Budair"},
    {"name": "Wadih Al Yamani", "country": "Arabie saoudite", "wiki_title": "Wadih_Al_Yamani"},
    {"name": "Rizgar Kurdi", "country": "Irak", "wiki_title": "Rizgar_Kurdi"},
    {"name": "Omar Al Kazabri", "country": "Maroc", "wiki_title": "Omar_Al_Kazabri"},
    {"name": "Younes Aswailis", "country": "Maroc", "wiki_title": "Younes_Aswailis"},
    {"name": "Abderrahmane Mossad", "country": "Algerie", "wiki_title": "Abderrahmane_Mossad"},
    {"name": "Salah Bukhatir", "country": "Emirats arabes unis", "wiki_title": "Salah_Bukhatir"},
    {"name": "Muhsin Al Qasim", "country": "Arabie saoudite", "wiki_title": "Muhsin_Al_Qasim"},
    {"name": "Ahmed Naina", "country": "Egypte", "wiki_title": "Ahmed_Naina"},
    {"name": "Sherif Mostafa", "country": "Egypte", "wiki_title": "Sherif_Mostafa"},
    {"name": "Abdelaziz Al Ahmad", "country": "Arabie saoudite", "wiki_title": "Abdelaziz_Al_Ahmad"},
    {"name": "Muhammad Al Luhaidan", "country": "Arabie saoudite", "wiki_title": "Muhammad_Al_Luhaidan"},
    {"name": "Ibrahim Al Akhdar", "country": "Arabie saoudite", "wiki_title": "Ibrahim_Al_Akhdar"},
    {"name": "Khalid Al Jalil", "country": "Arabie saoudite", "wiki_title": "Khalid_Al_Jalil"},
    {"name": "Abdurrahman Mossad", "country": "Algerie", "wiki_title": "Abderrahmane_Mossad"},
    {"name": "Yahya Hawwa", "country": "Syrie", "wiki_title": "Yahya_Hawwa"},
]
